### ISSUE TITLE
tests using propFunc() and mapTo() fail because the invoked mapped callback does not receive the real event argument

### ISSUE THREAD

**Issue by Fofir** [craigbilner/react-component-tester#60]
Let's say i have the following component class:

```
class MyComponent extends Component
{


    onChange( evt )
    {
        const { name, value } = evt.target;
        console.log( name, value );
    }


    render ()
    {
        return ( <input name="username" onChange={this.onChange} />)
    }

}
```

and the following test:
```
it( 'fires onChange', () =>
{
    const inputs = MY_COMPONENT.findComponents( 'input' );
    const isMapped = inputs[0].propFunc( 'onChange' ).mapsTo( 'onChange' );
    expect( isMapped ).toBe( true );
} );
```

This will fail because `evt.target` is undefined. 

From what i checked,  the `onInputChange` invoked  by the `propFunc/mapsTo` combination gets a different argument that the actual event, which is `Symbol(onChange)`.

My question is why is it so?

**Comment by craigbilner** [comment]
Hi @Fofir 

In order to guarantee that invoking the prop function is calling the expected method, rct resets the spy, calls the method with a unique value and checks that method was called with this unique value (a Symbol).

I had a think about how to do this better for your scenario but couldn't think of any nice practical ways of "knowing" the method signature that you were testing. It can't stub the method instead either because at this point it's too late and some methods that effect render need to be called rather than stubbed out which is hard to infer.

I've added a cheeky method called `withArgs` which allows you to mock the arguments for the method you're mapping to which allows you to test the method at will without cluttering it with defensive code.

Your other option would be something along the lines of:

```javascript
onChange({ target: { name, value } = {} } = {})
```

I guess this would make the method more robust but you might prefer to just assume you're going to get an `evt` object here, in which case you can now use `withArgs`.

If you have any other preferences let me know!

**Comment by Fofir** [comment]
Hi @craigbilner !

Thanks for the help. I will try and use `withArgs` and hopefully this solves my case.

I was thinking about using sinon stubs but couldn't figure it out yet. As you mentioned:

> It can't stub the method instead either because at this point it's too late and some methods that effect render need to be called rather than stubbed out which is hard to infer.
